version: '3.8'

services: 
  #backend (Laravel)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: nativo-backend
    container_name: app_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8001:8000"
    networks:
      - nativo-network
    depends_on:
      - db
  #base de datos (MySQL)
  db:
    image: mysql:8.0
    container_name: app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nativo-network
  #frontend (vue)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nativo-frontend
    container_name: app_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173" 
    networks:
      - nativo-network

networks:
  nativo-network:
    driver: bridge

volumes:
  dbdata: